use std::collections::HashMap;
use std::net::SocketAddr;
use std::sync::Arc;
use std::time::Duration;

use tokio::net::TcpListener;
use tokio::sync::Mutex;

use common::error::FfsError;
use consensus::RaftNode;

use crate::client::drive_round;
use crate::connection::TcpConnection;
use crate::message::{decode, encode, RaftMessage};

/// Drives one Raft node: accepts incoming RPCs and periodically ticks
/// the node, dispatching its outbox to peers over TCP.
pub struct RaftServer {
    listener: TcpListener,
    node: Arc<Mutex<RaftNode>>,
    peers: Arc<HashMap<u64, SocketAddr>>,
}

impl RaftServer {
    pub fn new(
        listener: TcpListener,
        node: Arc<Mutex<RaftNode>>,
        peers: HashMap<u64, SocketAddr>,
    ) -> Self {
        Self {
            listener,
            node,
            peers: Arc::new(peers),
        }
    }

    /// Run the accept loop and the driver loop concurrently.
    ///
    /// This future runs forever unless the listener fails.
    pub async fn run(self) -> Result<(), FfsError> {
        let RaftServer {
            listener,
            node,
            peers,
        } = self;

        // Driver task: ticks the node and flushes its outbox.
        let driver_node = node.clone();
        let driver_peers = peers.clone();
        tokio::spawn(async move {
            run_driver(driver_node, driver_peers).await;
        });

        // Accept loop.
        loop {
            let (stream, peer_addr) = listener.accept().await?;
            tracing::debug!("incoming connection from {peer_addr}");

            let node = node.clone();
            tokio::spawn(async move {
                if let Err(e) = handle_incoming(stream, node).await {
                    tracing::debug!("connection from {peer_addr} closed: {e}");
                }
            });
        }
    }
}

/// Driver loop: every 10 ms, tick the node, drain its outbox, and deliver
/// messages to peers. Repeats for a few rounds if handling replies
/// produces new outbox entries (e.g. becoming leader triggers heartbeats).
async fn run_driver(
    node: Arc<Mutex<RaftNode>>,
    peers: Arc<HashMap<u64, SocketAddr>>,
) {
    let mut interval = tokio::time::interval(Duration::from_millis(10));
    interval.set_missed_tick_behavior(tokio::time::MissedTickBehavior::Delay);

    loop {
        interval.tick().await;

        // 1. Tick and drain outbox.
        let outgoing = {
            let mut n = node.lock().await;
            n.tick();
            n.take_outbox()
        };

        // 2. Cascade through rounds until nothing new is produced.
        //    Capped to prevent runaway loops.
        let mut queue = outgoing;
        let mut rounds = 0;
        while !queue.is_empty() && rounds < 5 {
            queue = drive_round(queue, peers.clone(), node.clone()).await;
            rounds += 1;
        }
    }
}

/// Handle a single incoming connection: read one request, apply it to the
/// node, send the reply.
async fn handle_incoming(
    stream: tokio::net::TcpStream,
    node: Arc<Mutex<RaftNode>>,
) -> Result<(), FfsError> {
    let mut conn = TcpConnection::new(stream);
    let bytes = conn.recv().await?;
    let msg = decode(&bytes)?;

    let reply = {
        let mut n = node.lock().await;
        match msg {
            RaftMessage::RequestVote(req) => RaftMessage::RequestVoteReply {
                from: n.id,
                reply: n.handle_request_vote(req),
            },
            RaftMessage::AppendEntries(req) => RaftMessage::AppendEntriesReply {
                from: n.id,
                reply: n.handle_append_entries(req),
            },
            // We should never receive a reply on the server side.
            _ => {
                tracing::warn!("server received a reply message; ignoring");
                return Ok(());
            }
        }
        // Any outbox generated by handling the request is left in the node;
        // the driver loop will pick it up on its next tick.
    };

    conn.send(&encode(&reply)?).await?;
    Ok(())
}