[package]
name = "meta"
version = "0.1.0"
edition = "2021"

[dependencies]
common    = { path = "../common" }
consensus = { path = "../consensus" }
storage   = { path = "../storage" }
tokio     = { workspace = true }
tracing   = { workspace = true }
bincode   = { version = "2", features = ["serde"] }
dashmap   = "5"