[package]
name = "network"
version = "0.1.0"
edition = "2021"

[dependencies]
common    = { path = "../common" }
consensus = { path = "../consensus" }
tokio     = { workspace = true }
tracing   = { workspace = true }
serde     = { workspace = true }
bincode   = { version = "2", features = ["serde"] }