[package]
name = "fuse"
version = "0.1.0"
edition = "2021"

[dependencies]
common       = { path = "../common" }
storage      = { path = "../storage" }
vfs          = { path = "../vfs" }
meta         = { path = "../meta" }       # samo za InodeManager tip u mount.rs
consensus    = { path = "../consensus" }  # samo za RaftNode u mount.rs
fuse3        = { version = "0.9", features = ["tokio-runtime", "unprivileged"] }
tokio        = { workspace = true }
tracing      = { workspace = true }
tracing-subscriber = { version = "0.3" }
dashmap      = "5"
bytes        = "1"
libc         = "0.2"
futures-util = "0.3"